# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': '\u0430\u043a\u0446\u0438\u044e', 'verbose_name_plural': '\u0410\u043a\u0446\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.CharField(max_length=255, null=True, verbose_name='slug'),
        ),
    ]
