# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.CharField(help_text='\u041d\u0443\u0436\u0435\u043d \u0434\u043b\u044f URL', max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='\n                                   \u0415\u0441\u043b\u0438 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440 \u043f\u043e\u044f\u0432\u0438\u043b\u0430\u0441\u044c \u0441\u043a\u0438\u0434\u043a\u0430, \u0442\u043e \u0432\u043f\u0438\u0448\u0438\u0442\u0435 \u0435\u0433\u043e \u0441\u044e\u0434\u0430.<br>\n                                   \u041f\u043e\u0441\u043b\u0435 \u0442\u043e\u0433\u043e \u043a\u0430\u043a \u0432\u044b \u0432\u043f\u0438\u0448\u0438\u0442\u0435 \u0441\u043a\u0438\u0434\u043a\u0443 \u0446\u0435\u043d\u0430 \u0432\u0435\u0437\u0434\u0435 \u0441\u0442\u0430\u043d\u0435\u0442 \u0441 \u0443\u0447\u0451\u0442\u043e\u043c \u0441\u043a\u0438\u0434\u043a\u0438,<br>\n                                   \u041f\u043e\u044d\u0442\u043e\u043c\u0443 \u043c\u0435\u043d\u044f\u0442\u044c \u043f\u043e\u043b\u0435 "\u0426\u0435\u043d\u0430" \u043d\u0435 \u043d\u0443\u0436\u043d\u043e, \u0435\u0441\u043b\u0438 \u044d\u0442\u043e \u043d\u0435 \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f\n                                   ', null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440')),
                ('is_active', models.BooleanField(default=True, help_text='\n                                    \u041d\u0430 \u0441\u0430\u0439\u0442\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u044e\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e \u0442\u0435 \u0442\u043e\u0432\u0430\u0440\u044b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u043f\u043e\u043c\u0435\u0447\u0435\u043d\u044b "\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u043c"!<br>\n                                    \u041f\u043e\u044d\u0442\u043e\u043c\u0443 \u0432\u043c\u0435\u0441\u0442\u043e \u0442\u043e\u0433\u043e, \u0447\u0442\u043e\u0431\u044b \u0443\u0434\u0430\u043b\u0438\u0442\u044c \u0442\u043e\u0432\u0430\u0440 \u0438\u0437 \u0431\u0430\u0437\u044b \u043f\u0440\u043e\u0441\u0442\u043e \u0443\u0431\u0435\u0440\u0438\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443 "\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439"<br>\n                                    \u041f\u043e\u0441\u043b\u0435 \u044d\u0442\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440 \u043f\u0435\u0440\u0435\u0441\u0442\u0430\u043d\u0435\u0442 \u0431\u044b\u0442\u044c \u0432\u0438\u0434\u0435\u043d \u043d\u0430 \u0441\u0430\u0439\u0442\u0435\n                                    ', verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439?')),
                ('is_available', models.BooleanField(default=True, verbose_name='\u0415\u0441\u0442\u044c \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438?')),
                ('is_stock', models.BooleanField(default=False, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0443\u0435\u0442 \u0430\u043a\u0446\u0438\u044f?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u043a\u0443\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0420\u0430\u0441\u0446\u0432\u0435\u0442\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0446\u0432\u0435\u0442',
                'verbose_name_plural': '\u0420\u0430\u0441\u0446\u0432\u0435\u0442\u043a\u0430 \u0442\u043e\u0432\u0430\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0434\u043b\u044f \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0434\u043b\u044f \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='\u041f\u0435\u0440\u0435\u0434\u0432\u0438\u043d\u0442\u0435 \u043c\u044b\u0448\u043a\u043e\u0439')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('category', models.ForeignKey(help_text='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f, \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u043f\u0440\u0435\u043d\u0430\u0434\u043b\u0435\u0436\u0438\u0442 \u044d\u0442\u043e\u0442 \u0440\u0430\u0437\u043c\u0435\u0440', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='categories.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u044f')),
            ],
            options={
                'ordering': ('sort_order',),
                'verbose_name': '\u0440\u0430\u0437\u043c\u0435\u0440',
                'verbose_name_plural': '\u0420\u0430\u0437\u043c\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='ProductSizeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='\n            \u0412\u043d\u0438\u043c\u0430\u043d\u0438\u0435! \u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u043c\u043e\u0436\u0435\u0442 \u043e\u0431\u043d\u043e\u0432\u043b\u044f\u0442\u044c \u0434\u0430\u043d\u043d\u044b\u0435 \u043d\u0435 \u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u043e. \n            \u041f\u0440\u043e\u0441\u044c\u0431\u0430 \u043f\u0440\u043e\u0432\u0435\u0440\u044f\u0442\u044c \u0438\u043d\u0444\u043e\u0440\u0430\u0446\u0438\u044e \u043e \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0442\u043e\u0432\u0430\u0440\u0430 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435 <br>\n            ', validators=[django.core.validators.MinValueValidator(0)], verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSize', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440')),
            ],
            options={
                'verbose_name_plural': '\u0420\u0430\u0437\u043c\u0435\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='productcolor',
            name='size',
            field=models.ManyToManyField(to='product.ProductSizeSettings', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(help_text='\n        \u0412\u043d\u0438\u043c\u0430\u043d\u0438\u0435! \u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u043c\u043e\u0436\u0435\u0442 \u043e\u0431\u043d\u043e\u0432\u043b\u044f\u0442\u044c \u0434\u0430\u043d\u043d\u044b\u0435 \u043d\u0435 \u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u043e. \n        \u041f\u0440\u043e\u0441\u044c\u0431\u0430 \u043f\u0440\u043e\u0432\u0435\u0440\u044f\u0442\u044c \u0438\u043d\u0444\u043e\u0440\u0430\u0446\u0438\u044e \u043e \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0442\u043e\u0432\u0430\u0440\u0430 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435 <br>\n        ', related_name='product', to='product.ProductColor', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
    ]
