# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='size',
            field=models.ManyToManyField(to='product.ProductSize', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='productsizesettings',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSizeSettings', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440'),
        ),
    ]
