# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170901_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizesettings',
            options={'verbose_name_plural': '\u0421\u043a\u043b\u0430\u0434'},
        ),
    ]
