# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170903_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='product.Product', verbose_name='\u0442\u043e\u0432\u0430\u0440'),
        ),
    ]
