# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170903_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizesettings',
            name='without_size',
            field=models.BooleanField(default=False, verbose_name='\u0411\u0435\u0437 \u0440\u0430\u0437\u043c\u0435\u0440\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(blank=True, help_text='\n        \u0412\u043d\u0438\u043c\u0430\u043d\u0438\u0435! \u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u043c\u043e\u0436\u0435\u0442 \u043e\u0431\u043d\u043e\u0432\u043b\u044f\u0442\u044c \u0434\u0430\u043d\u043d\u044b\u0435 \u043d\u0435 \u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u043e. \n        \u041f\u0440\u043e\u0441\u044c\u0431\u0430 \u043f\u0440\u043e\u0432\u0435\u0440\u044f\u0442\u044c \u0438\u043d\u0444\u043e\u0440\u0430\u0446\u0438\u044e \u043e \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0442\u043e\u0432\u0430\u0440\u0430 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435 <br>\n        \u042d\u0442\u043e\u0442 \u0441\u043a\u043b\u0430\u0434 \u0434\u043b\u044f \u043e\u0434\u0435\u0436\u0434\u044b \u0438\u043b\u0438 \u0434\u043b\u044f \u0442\u043e\u0432\u0430\u0440\u043e\u0432 \u0443 \u043a\u043e\u0442\u043e\u0440\u044b\u0445 \u0435\u0441\u0442\u044c \u0440\u0430\u0437\u043c\u0435\u0440 \u0438\u043b\u0438 \u0446\u0432\u0435\u0442\n        ', related_name='product', to='product.ProductColor', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
        migrations.AlterField(
            model_name='productsizesettings',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSize', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440'),
        ),
    ]
