# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170903_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizesettings',
            name='without_size',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='without_size',
            field=models.BooleanField(default=False, verbose_name='\u0411\u0435\u0437 \u0440\u0430\u0437\u043c\u0435\u0440\u043e\u0432'),
        ),
    ]
