# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170904_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='without_size',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u0420\u0430\u0441\u0446\u0432\u0435\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='product',
            name='without_size',
            field=models.BooleanField(default=False, verbose_name='\u0411\u0435\u0437 \u0440\u0430\u0437\u043c\u0435\u0440\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='category',
            field=models.ForeignKey(help_text='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f, \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u043f\u0440\u0435\u043d\u0430\u0434\u043b\u0435\u0436\u0438\u0442 \u044d\u0442\u043e\u0442 \u0440\u0430\u0437\u043c\u0435\u0440', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='categories.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
