# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 06:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20171222_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='documentation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430\u0446\u0438\u044f'),
        ),
    ]
