# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0441\u0432\u0439\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u0412\u0441\u0435 \u0441\u0432\u043e\u0439\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.AllProductProperties', verbose_name='\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u043e'),
        ),
    ]
