# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='prop_tip',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430 \u0434\u043b\u044f \u0441\u0432\u043e\u0439\u0441\u0442\u0432\u0430!'),
        ),
    ]
