# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productproperty_prop_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
