# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20180112_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consumption',
            field=models.FloatField(default=0.0, verbose_name='\u0420\u0430\u0441\u0445\u043e\u0434 \u043d\u0430 \u043c(2,3)'),
        ),
    ]
