# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.CharField(max_length=10000, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
