# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20180131_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='\u0412\u0435\u0441 (\u043a\u0433)'),
        ),
    ]
