# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='thickness',
            field=models.PositiveIntegerField(),
        ),
    ]
