# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20180501_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consumption',
            field=models.FloatField(default=0.0, verbose_name='\u0420\u0430\u0441\u0445\u043e\u0434 \u0432 \u043a\u0438\u043b\u043e\u0433\u0440\u0430\u043c\u043c\u0430\u0445 \u043d\u0430 \u043c\u0435\u0442\u0440 \u043a\u0443\u0431'),
        ),
    ]
