# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20180523_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.FileField(upload_to='price_list/', verbose_name='\u0424\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0430\u0439\u0441 \u043b\u0438\u0441\u0442',
                'verbose_name_plural': '\u041f\u0440\u0430\u0439\u0441 \u043b\u0438\u0441\u0442\u044b',
            },
        ),
    ]
