# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_pricelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': '\u043f\u0440\u0430\u0439\u0441 \u043b\u0438\u0441\u0442', 'verbose_name_plural': '\u041f\u0440\u0430\u0439\u0441 \u043b\u0438\u0441\u0442\u044b'},
        ),
    ]
