# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20180530_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproductproperties',
            options={'verbose_name': '\u0441\u0432\u043e\u0439\u0441\u0442\u0432\u043e', 'verbose_name_plural': '\u0412\u0441\u0435 \u0441\u0432\u043e\u0439\u0441\u0442\u0432\u0430'},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
