# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20180503_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='calculation_category',
        ),
        migrations.DeleteModel(
            name='CalculationCategory',
        ),
    ]
