# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 15:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0442\u0435\u043a\u0441\u0442\u0430')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439',
            },
        ),
    ]
