# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_auto_20171222_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('number', models.CharField(max_length=255, verbose_name='\u0426\u0438\u0444\u0440\u044b')),
            ],
            options={
                'verbose_name': '\u0446\u0438\u0444\u0440\u044b',
                'verbose_name_plural': '\u041c\u044b \u0432 \u0446\u0438\u0444\u0440\u0430\u0445',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_team/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440')),
                ('profession', models.CharField(max_length=255, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u0438 \u0438\u043c\u044f')),
            ],
            options={
                'verbose_name_plural': '\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='about_in_numbers',
            field=models.ManyToManyField(blank=True, to='client_app.AboutInNumbers', verbose_name='\u041c\u044b \u0432 \u0446\u0438\u0444\u0440\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='about',
            name='team',
            field=models.ManyToManyField(blank=True, to='client_app.OurTeam', verbose_name='\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
    ]
