# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_auto_20171222_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('email', models.CharField(max_length=255, verbose_name='E-Mail')),
                ('message', models.TextField(max_length=10000, verbose_name='\u041e\u0442\u0437\u044b\u0432')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u043e\u0442\u0437\u044b\u0432\u0430')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u0412\u0438\u0434\u0438\u043c\u044b\u0439 \u043e\u0442\u0437\u044b\u0432')),
            ],
            options={
                'verbose_name': '\u043e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
    ]
