# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AGB',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='HowToOrder',
        ),
        migrations.DeleteModel(
            name='Impressum',
        ),
    ]
