# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_auto_20171222_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_time',
        ),
    ]
