# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 18:32
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_auto_20171224_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='\u041c\u0435\u0441\u0442\u043e\u043d\u0430\u0445\u043e\u0436\u0434\u0435\u043d\u0438\u0435 \u0444\u0438\u043b\u0438\u0430\u043b\u043b\u0430'),
        ),
    ]
