# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_article'),
        ('client_app', '0018_slider_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.AllProductProperties', verbose_name='\u0423\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u044c \u0432\u0435\u0441\u0430'),
        ),
    ]
