# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_sitesettings_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0443', 'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430'},
        ),
    ]
