# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 15:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0020_auto_20171225_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='order',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0441\u0442\u043e \u0437\u0430\u043a\u0430\u0437\u0430\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u041b\u0435\u0433\u043a\u043e \u0437\u0430\u043f\u043b\u0430\u0442\u0438\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promotions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0438 \u0438 \u0430\u043a\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u041d\u0430\u043c \u0434\u043e\u0432\u0435\u0440\u044f\u044e\u0442'),
        ),
    ]
