# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 15:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0021_auto_20180112_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430'),
        ),
    ]
