# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20171225_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
