# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='order/', verbose_name='Excel \u0444\u0430\u0439\u043b'),
        ),
    ]
